import MySQLdb

from PyQt4 import QtGui

import sys


class Ventana(QtGui.QWidget):

    def __init__(self):
        super(Ventana, self).__init__()

        self.setWindowTitle("Biblioteca")

        self.resize(450, 350)

        self.conn = MySQLdb.connect(host="localhost", user="root", passwd="123456", db="library")
        self.cursor = self.conn.cursor()

        self.label1 = QtGui.QLabel("Username", self)
        self.label2 = QtGui.QLabel("Password", self)
        self.label3 = QtGui.QLabel("Bienvenido al Sistema de Biblioteca", self)
        self.label4 = QtGui.QLabel("Nuevo usuario ------>", self)
        self.label5 = QtGui.QLabel("Bienvenido al Sistema de Biblioteca", self)
        self.label6 = QtGui.QLabel("Bienvenido al Sistema de Biblioteca ", self)
        self.label7 = QtGui.QLabel("Usernamenndjhdjdjdjdjdjddhdhdh hdhd", self)
        self.button1 = QtGui.QPushButton("Aceptar", self)
        self.button2 = QtGui.QPushButton("Registrar", self)
        self.button3 = QtGui.QPushButton("Registrar", self)
        self.button4 = QtGui.QPushButton("Cancelar", self)
        self.button5 = QtGui.QPushButton("Aceptar", self)
        self.button6 = QtGui.QPushButton("Ver Lista de Usuarios", self)
        self.button7 = QtGui.QPushButton("Aceptar", self)
        self.lineEdit1 = QtGui.QLineEdit(self)
        self.lineEdit2 = QtGui.QLineEdit(self)
        self.lineEdit3 = QtGui.QLineEdit(self)
        self.lineEdit4 = QtGui.QLineEdit(self)
        self.lineEdit5 = QtGui.QLineEdit(self)
        self.lineEdit6 = QtGui.QLineEdit(self)
        self.lineEdit7 = QtGui.QLineEdit(self)
        self.lineEdit8 = QtGui.QLineEdit(self)
        self.textEdit1 = QtGui.QTextEdit("",self)
        self.textEdit1.setGeometry(20, 60, 650 , 500)
        self.textEdit1.hide()
        self.label1.move(90, 100)
        self.label2.move(90, 130)
        self.label3.move(135, 20)
        self.label4.move(150, 215)
        self.button1.move(300, 99)
        self.lineEdit1.move(150, 100)
        self.lineEdit2.move(150, 130)
        self.button2.move(300, 210)
        self.label5.hide()
        self.label6.hide()
        self.label7.hide()
        self.lineEdit3.hide()
        self.lineEdit4.hide()
        self.lineEdit5.hide()
        self.lineEdit6.hide()
        self.lineEdit7.hide()
        self.lineEdit8.hide()
        self.button3.hide()
        self.button4.hide()
        self.button5.hide()
        self.button6.hide()
        self.lineEdit1.setGeometry(150, 100, 135, 20)
        self.lineEdit2.setGeometry(150, 130, 135, 20)
        self.lineEdit1.setText("")
        self.lineEdit2.setText("")
        self.lineEdit3.setText("")
        self.lineEdit4.setText("")
        self.lineEdit5.setText("")
        self.lineEdit6.setText("")
        self.lineEdit7.setText("")
        self.lineEdit8.setText("")
        self.lineEdit2.setEchoMode(QtGui.QLineEdit.Password)
        self.lineEdit8.setEchoMode(QtGui.QLineEdit.Password)
        self.button1.clicked.connect(self.iniciarBase)
        self.button2.clicked.connect(self.insertarNuevoUsuario)
        self.button3.clicked.connect(self.registrandoNuevoUsuario)
        self.button4.clicked.connect(self.cargarVentanaInicial)
        self.button5.clicked.connect(self.interfazBaseDatos)
        self.button6.clicked.connect(self.listarUsuarios)
        self.button7.clicked.connect(self.cargarVentanaInicial)
        self.button6.move(680,80)
        self.button7.hide()
        self.contraVentanaInicial = ""
        self.contraRegistro = ""

        #self.cursor.execute("SELECT * from usuario")
        #renglon = self.cursor.fetchall()
        #print(renglon)

    def insertarNuevoUsuario(self):
        self.label1.setText("Direccion")
        self.label2.setText("Municipio")
        self.label1.move(65, 120)
        self.label2.move(65, 160)
        self.label3.setText("Registro de Nuevo Usuario")
        self.label3.move(210, 30)
        self.label4.setText("Nombre de usuario")
        self.label4.move(65, 80)
        self.label5.setVisible(True)
        self.label5.setText("Estado")
        self.label5.move(65, 200)
        self.label6.setVisible(True)
        self.label6.setText("Email")
        self.label7.setVisible(True)
        self.label6.move(65, 240)
        self.label7.setText("Password")
        self.label7.move(65, 280)
        self.resize(550, 430)
        self.move(350, 150)
        self.lineEdit3.setVisible(True)
        self.lineEdit4.setVisible(True)
        self.lineEdit5.setVisible(True)
        self.lineEdit6.setVisible(True)
        self.lineEdit1.setGeometry(180, 80, 250, 20)
        self.lineEdit8.setGeometry(180, 280, 250, 20)
        self.lineEdit3.setGeometry(180, 120, 250, 20)
        self.lineEdit4.setGeometry(180, 160, 250, 20)
        self.lineEdit5.setGeometry(180, 200, 250, 20)
        self.lineEdit6.setGeometry(180, 240, 250, 20)
        self.button1.hide()
        self.button2.hide()
        self.button5.hide()
        self.lineEdit2.hide()
        self.button3.setVisible(True)
        self.button4.setVisible(True)
        self.button4.move(310, 340)
        self.button3.move(210, 340)
        self.lineEdit1.setText("")
        self.lineEdit8.setText("")
        self.lineEdit3.setText("")
        self.lineEdit4.setText("")
        self.lineEdit5.setText("")
        self.lineEdit6.setText("")
        if (self.label4.isEnabled() == True):
            self.label4.setVisible(True)
        if (self.lineEdit8.isEnabled() == True):
            self.lineEdit8.setVisible(True)

    def cargarVentanaInicial(self):
        self.resize(450, 350)
        self.label1.setText("Username")
        self.label2.setText("Password")
        self.label3.setText("Bienvenido al Sistema de Biblioteca")
        self.label4.setText("Nuevo usuario ------>")
        self.label5.setText("Bienvenido al Sistema de Biblioteca kdkdkdkd")
        self.label6.setText("Bienvenido al Sistema de Biblioteca jjdjdjd")
        self.label7.setText("Usernamenndjhdjdjdjdjdjddhdhdh hdhdhdhdhdhdjhd")
        self.button1.setText("Aceptar")
        self.button2.setText("Registrar")
        self.button3.setText("Registrar")
        self.button4.setText("Cancelar")
        self.label1.move(80, 100)
        self.label2.move(80, 130)
        self.label3.move(135, 20)
        self.label4.move(150, 215)
        self.button1.move(300, 99)
        self.lineEdit1.move(150, 100)
        self.lineEdit2.move(150, 130)
        self.button2.move(300, 210)
        self.label5.hide()
        self.label6.hide()
        self.label7.hide()
        self.lineEdit3.hide()
        self.lineEdit4.hide()
        self.lineEdit5.hide()
        self.lineEdit6.hide()
        self.lineEdit8.hide()
        self.button3.hide()
        self.button4.hide()
        self.button5.hide()
        self.button7.hide()
        self.button1.setVisible(True)
        self.button2.setVisible(True)
        self.lineEdit1.setGeometry(140, 100, 145, 20)
        self.lineEdit2.setGeometry(140, 130, 145, 20)
        self.lineEdit1.setText("")
        self.lineEdit2.setText("")
        self.lineEdit3.setText("")
        self.lineEdit4.setText("")
        self.lineEdit5.setText("")
        self.lineEdit6.setText("")
        if(self.lineEdit1.isEnabled() == True):
            self.lineEdit1.setVisible(True)
        if (self.lineEdit2.isEnabled() == True):
            self.lineEdit2.setVisible(True)
        if(self.label1.isEnabled() == True):
            self.label1.setVisible(True)
        if (self.label2.isEnabled() == True):
            self.label2.setVisible(True)
        if (self.label4.isEnabled() == True):
            self.label4.setVisible(True)



    def iniciarBase(self):
        nombre = "'"+str(self.lineEdit1.text()+"'")
        contra = "'"+str(self.lineEdit2.text()+"'")
        self.cursor.execute("SELECT * from usuario where username =%s" %(nombre))
        datos = self.cursor.fetchone()

        if(datos != None):
            if(datos[1] == str(self.lineEdit1.text()) and datos[6] == str(self.lineEdit2.text())):
                self.resize(250, 100)
                self.move(500, 250)
                self.label2.hide()
                self.label3.hide()
                self.label1.hide()
                self.label5.hide()
                self.label6.hide()
                self.label7.hide()
                self.button1.hide()
                self.button3.hide()
                self.button2.hide()
                self.button4.hide()
                self.lineEdit1.hide()
                self.lineEdit2.hide()
                self.lineEdit3.hide()
                self.lineEdit4.hide()
                self.lineEdit5.hide()
                self.lineEdit6.hide()
                self.lineEdit8.hide()
                self.label4.move(90, 15)
                self.label4.setText("Login Correcto")
                self.button5.setVisible(True)
                self.button5.move(86, 50)

    def interfazBaseDatos(self):
        self.resize(800, 600)
        self.move(220, 50)
        self.label4.hide()
        self.button5.hide()
        self.button6.setVisible(True)
        self.textEdit1.setVisible(True)

    def registrandoNuevoUsuario(self):
        if(self.lineEdit1.text() != "" and self.lineEdit8.text() != "" and self.lineEdit3.text() != "" and self.lineEdit4.text() != "" and self.lineEdit5.text() != "" and self.lineEdit6.text() != "" ):
            nombreUsuario = str(self.lineEdit1.text())
            contrasenaUsuario = str(self.lineEdit8.text())
            direccionUsuario = str(self.lineEdit3.text())
            estadoUsuario = str(self.lineEdit5.text())
            correoUsuario= str(self.lineEdit6.text())
            municipioUsuario = str(self.lineEdit4.text())
            self.cursor.execute("""INSERT INTO usuario (username, direccion, municipio, estado, email, contrasena) VALUES('%s','%s','%s','%s','%s','%s')""" % (nombreUsuario,direccionUsuario, municipioUsuario, estadoUsuario, correoUsuario,contrasenaUsuario))
            self.conn.commit()
            self.registroCorrecto()
            #self.cargarVentanaInicial()

    def listarUsuarios(self):
        self.textEdit1.clear()
        self.cursor.close()
        self.conn.close()
        self.conn = MySQLdb.connect(host="localhost", user="root", passwd="123456", db="library")
        self.cursor = self.conn.cursor()
        self.cursor.execute("SELECT * from usuario")
        renglon = self.cursor.fetchall()
        i = 0
        j =0
        data = ""

        while(i<len(renglon)):
            j = 0
            while(j<7):
                self.textEdit1.insertPlainText(str(renglon[i][j]))
                self.textEdit1.insertPlainText(" || ")
                j = j+1
            i = i+1
            self.textEdit1.insertPlainText("\n")

    def registroCorrecto(self):
        self.label1.hide()
        self.label2.hide()
        self.label4.hide()
        self.label5.hide()
        self.label6.hide()
        self.label7.hide()
        self.lineEdit1.hide()
        self.lineEdit2.hide()
        self.lineEdit3.hide()
        self.lineEdit4.hide()
        self.lineEdit5.hide()
        self.lineEdit6.hide()
        self.lineEdit7.hide()
        self.lineEdit8.hide()
        self.button1.hide()
        self.button2.hide()
        self.button3.hide()
        self.button4.hide()
        self.button5.hide()
        self.button6.hide()
        self.button7.setVisible(True)
        self.resize(250, 100)
        self.move(500, 250)
        self.label3.move(90, 15)
        self.label3.setText("Registro Correcto")
        self.button7.setVisible(True)
        self.button7.move(86, 50)




app = QtGui.QApplication(sys.argv)

ventana = Ventana()
ventana.show()
sys.exit(app.exec_())
ventana.cursor.close()
ventana.conn.close()